# Generated by Django 4.2.5 on 2023-10-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=2083)),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('genre', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
