# Generated by Django 4.2.5 on 2023-10-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_book_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
    ]
