# Generated by Django 4.2.5 on 2023-10-18 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_book_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='max_age',
        ),
    ]
