# Generated by Django 4.2.5 on 2023-10-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.CharField(max_length=2083),
        ),
    ]
