# Generated by Django 4.2.5 on 2023-10-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_review_rating_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rec',
            field=models.BooleanField(null=True),
        ),
    ]
